### ISSUE TITLE
Invalid position returned in ArrayAdapter

### ISSUE THREAD

**Issue by Fedor-Tsyganov** [baoyongzhang/SwipeMenuListView#26]
Tested versus regular ListView and correct position was returned, but SwipeMenuListView returns invalid position.

I have an array of 38 objects and using simple getView(int position, View convertView, ViewGroup parent) method to return a custom view.

Here's log file to show how it works with SwipeMenuListView and regular ListView

SwipeMenuListView - Invalid position example:
03-14 01:29:43.717    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.718    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.718    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.719    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.720    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 01:29:43.721    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 5
03-14 01:29:43.721    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 6
03-14 01:29:43.721    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 7
03-14 01:29:43.722    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.722    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.723    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.724    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.725    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 01:29:43.726    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 5
03-14 01:29:43.726    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 6
03-14 01:29:43.727    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 7
03-14 01:29:43.727    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.728    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.728    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.729    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.729    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 01:29:43.731    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 5
03-14 01:29:43.731    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 6
03-14 01:29:43.731    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 7
03-14 01:29:43.732    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.732    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.733    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.733    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.734    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 01:29:43.734    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 5
03-14 01:29:43.735    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 6
03-14 01:29:43.735    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 7
03-14 01:29:43.736    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.737    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.738    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.739    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.740    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 01:29:43.740    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 5
03-14 01:29:43.741    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 6
03-14 01:29:43.742    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 7
03-14 01:29:43.748    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.748    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.749    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.749    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.749    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 01:29:43.750    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.750    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.750    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.750    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.751    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.751    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.751    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.752    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3
03-14 01:29:43.752    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 01:29:43.752    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 0
03-14 01:29:43.752    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 1
03-14 01:29:43.753    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 2
03-14 01:29:43.753    3052-3052/com.fedortsyganov.iptest I/Position﹕ -> 3

ListView - valid position example:
03-14 02:06:58.644    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 4
03-14 02:06:58.660    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 5
03-14 02:06:58.678    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 6
03-14 02:06:58.694    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 7
03-14 02:06:58.694    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 8
03-14 02:06:58.710    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 9
03-14 02:06:58.731    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 10
03-14 02:06:58.732    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 11
03-14 02:06:58.743    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 12
03-14 02:06:58.762    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 13
03-14 02:06:58.777    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 14
03-14 02:06:58.778    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 15
03-14 02:06:58.794    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 16
03-14 02:06:58.811    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 17
03-14 02:06:58.828    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 18
03-14 02:06:58.846    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 19
03-14 02:06:58.846    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 20
03-14 02:06:58.863    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 21
03-14 02:06:58.877    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 22
03-14 02:06:58.894    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 23
03-14 02:06:58.912    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 24
03-14 02:06:58.927    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 25
03-14 02:06:58.929    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 26
03-14 02:06:58.944    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 27
03-14 02:06:58.961    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 28
03-14 02:06:58.977    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 29
03-14 02:06:58.994    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 30
03-14 02:06:59.012    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 31
03-14 02:06:59.028    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 32
03-14 02:06:59.045    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 33
03-14 02:06:59.061    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 34
03-14 02:06:59.077    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 35
03-14 02:06:59.094    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 36
03-14 02:06:59.110    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 37
03-14 02:06:59.128    4842-4842/com.fedortsyganov.iptest I/Position﹕ -> 30

**Comment by Fedor-Tsyganov** [comment]
Ok, I figured out what caused this problem.
In SwipeMenuAdapter.java under getView() method you need explicitly inflate view, thus removing 
this line:
    if (convertView == null)

and then remove this block:

else
        {
            layout = (SwipeMenuLayout) convertView;
            layout.closeMenu();
            layout.setPosition(position);
            View view = mAdapter.getView(position, layout.getContentView(), parent);
        }

**Comment by kekeu** [comment]
This problem has been resolved in version 1.3?
