### ISSUE TITLE
把这个放在viewpager里面,该怎么设置才能划出来?

### ISSUE THREAD

**Issue by 2ndtonone** [baoyongzhang/SwipeMenuListView#98]

**Comment by vip2193** [comment]
不能放在viewpager里面  他们两个的滑动冲突了

**Comment by Ucoon** [comment]
放在viewpager 怎么解决他们两个的滑动冲突？？有办法吗

**Comment by windvip** [comment]
重写下ViewPager

@Override     
public boolean onTouchEvent(MotionEvent ev) {         
    return isScrollable && super.onTouchEvent(ev);     
}
@Override     
public boolean onInterceptTouchEvent(MotionEvent ev) {
     return isScrollable && super.onInterceptTouchEvent(ev);     
}
